- name: Download repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Start docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Get Runner token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept:application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/prashumps/actions/runners/registration-token | jq .token | xargs
  delegate_to: localhost
  register: gh_auth_token

- name: Create runner containers
  loop:
    - runner-1
    - runner-2
    - runner-3
  community.docker.docker_container:
    name: "{{ item }}"
    image: prasanthreddymps/github-runner
    state: started
    pull: always
    restart: true
    restart_policy: always
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:ORG token={{ token }} url=http://vault-int.prashumps.online:8200') }}"
      TOKEN: "{{ gh_auth_token.stdout }}"
      NAME: "{{ item }}"
      ARM_CLIENT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_ID token={{ token }} url=http://vault-int.prashumps.online:8200') }}"
      ARM_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_SECRET token={{ token }} url=http://vault-int.prashumps.online:8200') }}"
      ARM_TENANT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_TENANT_ID token={{ token }} url=http://vault-int.prashumps.online:8200') }}"
